/*
 * Automatically generated by make menuconfig: don't edit
 */
#define AUTOCONF_INCLUDED

/** Static start address of binary (must be aligned to 1MBytes (2^20 bytes)) */
#define CONFIG_START_ADDRESS 0x00100000

/** CCSR block base address as configured by U-Boot */
#define CONFIG_CCSR_BASE (0xF8000000)

/** Stack size in Kbytes */
#define CONFIG_STACK_SIZE (8)

/** Number of hardware IRQ sources supported by the PIC (including the internal sources) */
#define CONFIG_NO_HWIRQS (84)
/** Number of Message Signaled Interrupt Registers supported by the PIC */
#define CONFIG_PIC_NUM_MSIR (8)

/** Kernel MSR value */
#if defined(CONFIG_USE_ALTIVEC)
#define KERNEL_MSR_ALTIVEC  (MSR_VEC)
#else
#define KERNEL_MSR_ALTIVEC  (0)
#endif /* defined(CONFIG_USE_ALTIVEC) */

#if defined(CONFIG_USE_FPU)
#define KERNEL_MSR_FPU      (MSR_FP)
#else
#define KERNEL_MSR_FPU      (0)
#endif /* defined(CONFIG_USE_FPU) */

/* Machine-check enabled (ME), Instruction (IR) and
 * Data (DR) storage address translation enabled,
 * External interrupts (EE) disabled (= 0),
 * Interrupt prefix for high-addressed exceptions. */
#define KERNEL_MSR (MSR_ME | MSR_IP | MSR_IR | MSR_DR | KERNEL_MSR_FPU | KERNEL_MSR_ALTIVEC)

#define CONFIG_MPC8641HPCN 1
#define CONFIG_UART_DUART 1
#define CONFIG_BOARD "mpc8641hpcn"
#define CONFIG_CPU "e600"

#ifndef __ASSEMBLY__

/* Basic types */
typedef unsigned char uint8_t;
typedef char int8_t;
typedef unsigned short uint16_t;
typedef short int16_t;
typedef unsigned int uint32_t;
typedef int int32_t;
typedef unsigned long long uint64_t;
typedef long long int64_t;

#endif /* !defined(__ASSEMBLY__) */

